# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

stages:
# Build stage
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: ubuntu-latest

    variables:
      buildConfiguration: 'Release'

    steps:

    # install 6.0.x SDK
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        version: '6.0.x'

    # restore dependencies
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: 'src/*.csproj'

    # build the dotnet app inside the folder src
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: 'src/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
        
    # Publish artifacts & create a zip file as output for deployment
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True        

    # Publish build artifacts  
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# Deploy stage       
- stage: Deploy
  jobs:
  - job: Deploy

    pool:
      vmImage: ubuntu-latest

    steps:  

    # Download build artifacts
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(System.ArtifactsDirectory)'
        artifactName: 'drop'
        
    # Deploy the code to Azure Web App
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'MCAPS-Hybrid-REQ-38377-2022-abhinabsarkar(9c5ca55e-ea9c-4a3f-b1be-87c76fc15cf8)'
        appType: 'webAppLinux'
        WebAppName: 'wa-abhi-dev'
        packageForLinux: '$(System.ArtifactsDirectory)/drop/*.zip'
        RuntimeStack: 'DOTNETCORE|6.0'

