# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# install 6.0.x SDK
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '6.0.x'
# restore dependencies
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: 'src/*.csproj'
# build the dotnet app inside the folder src
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'src/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
